name: Express Testing
on:
  push:
    branches: [main]

jobs:
  jesttesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env: 
          CI: true